### ISSUE TITLE
✨[Feature] AFcreate物品创建优化 当主手为空气时，设置为默认材质

### ISSUE THREAD

**Issue by luoxiawuchen** [rokukoo/AzureFlow-issues#10]
官方WIKI：https://rokuko.gitbook.io/azureflow

### 反馈须知
- [X] 已查阅wiki不存在该功能

### 功能描述
> 请描述您的想法，该功能的意义、作用

建议：当主手为空气时，设置为默认材质（可在配置文件中设置）
或提示必须手持一个物品，并取消创建

### 备注信息
> 需要额外说明的内容

无

**Comment by rokukoo** [comment]
感谢您的建议，请及时注意交流群中的版本更新。
