### ISSUE TITLE
✨[Feature] /af list物品列表优化建议

### ISSUE THREAD

**Issue by luoxiawuchen** [rokukoo/AzureFlow-issues#11]
官方WIKI：https://rokuko.gitbook.io/azureflow

### 反馈须知
- [X] 已查阅wiki不存在该功能

### 功能描述
> 请描述您的想法，该功能的意义、作用

**为列表参数添加tab补齐提示**
为/af list命令查看物品列表 的可选参数（--m --s）添加tab补齐提示

**物品list聊天栏简化UI**
当不加参数时，/af list 可以直接将物品列表形式在聊天栏中，可以通过点击文本，切换页码
移动到对应物品名时，可以查看物品的详细描述（tiptools）

### 备注信息
> 需要额外说明的内容

无

**Comment by rokukoo** [comment]
感谢您的建议，请及时注意交流群中的版本更新。
