### ISSUE TITLE
🐛 [BUG] 手持MOD物品创建时，material无法正常填入modid

### ISSUE THREAD

**Issue by luoxiawuchen** [rokukoo/AzureFlow-issues#12]
官方WIKI：https://rokuko.gitbook.io/azureflow
描述清晰，排版整洁，错误日志详细的反馈通常会优先处理

### 反馈须知
- [X] 我已详细查阅wiki
- [X] 我已正确安装相关依赖

### 服务端类型
> 请填写您的服务端类型与Minecraft版本
> 如：spigot-1.16.5、paper-1.18.2

catserver-1.16.5、mohist-1.16.5、arclight-1.16.5
-----------------------------

### 错误描述
> 请详细地描述您遇到的问题

当手持MOD物品创建时，material无法正常填入modid，会显示为AIR&LEGACY_AIR
需要手动删除，并修改为对应MODID，并重载插件，material才能被正常载入mod物品
当然，这或许并不是AF的问题，毕竟是直接获取bukkit的枚举，而服务端一般会将物品注册进bukkit

### 错误日志
> 建议将错误日志上传至 https://paste.ubuntu.com/
> 并以链接形式提交

无

### 备注信息
> 需要额外说明的内容

无

**Comment by rokukoo** [comment]
v1.0.2.4最新版本已修复
