### ISSUE TITLE
✨[Feature] 新增trigger类型：onGenerate 物品生成

### ISSUE THREAD

**Issue by luoxiawuchen** [rokukoo/AzureFlow-issues#14]
官方WIKI：https://rokuko.gitbook.io/azureflow

### 反馈须知
- [x] 已查阅wiki不存在该功能

### 功能描述
> 请描述您的想法，该功能的意义、作用

onGenerate 当物品生成后，执行动作流。

**用途/使用例子：**
- 当装备品质是 极品的时候 全服公告；
- 当物品生成好以后，执行任意插件指令，形成联动。

### 备注信息
> 需要额外说明的内容

无

**Comment by rokukoo** [comment]
目前已有 onCreate 触发器，可使用该触发器实现需求

感谢您的建议，请及时注意交流群中的版本更新。
