### ISSUE TITLE
🐛 [BUG] 问题#9补充，高版本中部分物品材质无法被正常应用

### ISSUE THREAD

**Issue by luoxiawuchen** [rokukoo/AzureFlow-issues#17]
官方WIKI：https://rokuko.gitbook.io/azureflow
描述清晰，排版整洁，错误日志详细的反馈通常会优先处理

### 反馈须知
- [X] 我已详细查阅wiki
- [X] 我已正确安装相关依赖

### 服务端类型
> 请填写您的服务端类型与Minecraft版本
> 如：spigot-1.16.5、paper-1.18.2

spigot-1.16.5
--------------------------------------

### 错误描述
> 请详细地描述您遇到的问题

此问题是 #9 的补充，
当高低版本的材质枚举值完全不同时，将导致材质功能完全失效，无法被正常应用
例如：木剑 1.12是 wood_sword 而在1.13+（或更高版本）为 wooden_sword
由于只识别 wood_sword（旧版枚举），又由于高版本不存在此ID，导致该数值无效，物品材质无法正常应用。

### 错误日志
> 建议将错误日志上传至 https://paste.ubuntu.com/
> 并以链接形式提交

无

### 备注信息
> 需要额外说明的内容

无

**Comment by rokukoo** [comment]
v1.0.2.4最新版本已修复
