### ISSUE TITLE
✨[Feature] 建议新增onDamage触发器

### ISSUE THREAD

**Issue by EasonYiXun** [rokukoo/AzureFlow-issues#19]
官方WIKI：https://rokuko.gitbook.io/azureflow

### 反馈须知
- [x] 已查阅wiki不存在该功能

### 功能描述
> onDamaged触发器

允许当玩家（或实体）受到伤害时，触发实体受伤事件，并执行相应的动作

### 备注信息
> 需要额外说明的内容

无

**Comment by rokukoo** [comment]
onDamage 触发器目前版本暂无计划更新，因为onDamage触发器并非玩家物品主动触发，但用户可通过拦截器变相实现，具体可查阅wiki或交流群中询问获取帮助。

感谢您的建议，请及时注意交流群中的版本更新。
