### ISSUE TITLE
🐛 [BUG] sound动作无法填写参数的bug

### ISSUE THREAD

**Issue by alexskim** [rokukoo/AzureFlow-issues#21]
官方WIKI：https://rokuko.gitbook.io/azureflow
描述清晰，排版整洁，错误日志详细的反馈通常会优先处理

### 反馈须知
- [X] 我已详细查阅wiki
- [X] 我已正确安装相关依赖

### 服务端类型
> 请填写您的服务端类型与Minecraft版本
> 如：spigot-1.16.5、paper-1.18.2

paper-1.20.1
AzureFlow-1.0.2.3-rc2-build-40620-all.jar
--------------------------------------

### 错误描述
> 请详细地描述您遇到的问题

在使用sound这个action时如果添加了参数，在获取Sound枚举的时候会把参数也带进去

### 错误日志
> 建议将错误日志上传至 https://paste.ubuntu.com/
> 并以链接形式提交

>Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.ITEM_SHIELD_BREAK 1 1
        at java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.Sound.valueOf(Sound.java:13) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.rokuko.azureflow.features.resolver.provided.player.SoundResolver.doAction(SoundResolver.kt:16) ~[AzureFlow-1.0.2.3-rc2-build-40620-all.jar:?]

### 备注信息
> 需要额外说明的内容

在查看SoundResolver.doAction源代码后发现
`player.playSound(player.getLocation(), Sound.valueOf(StringsKt.trim(args).toString().toUpperCase(Locale.ROOT)), 1.0F, 1.0F);`
sound直接将它的参数获取Sound枚举，并且音量和音高固定1F

**Comment by rokukoo** [comment]
感谢您的反馈，请及时注意交流群中的版本更新。

**Comment by rokukoo** [comment]
v1.0.2.4已修复
