### ISSUE TITLE
✨[Feature] Add new action "remove-potion"

### ISSUE THREAD

**Issue by Yuusha103** [rokukoo/AzureFlow-issues#23]
官方WIKI：https://rokuko.gitbook.io/azureflow

### 反馈须知
- [√] 已查阅wiki不存在该功能

### 功能描述
> 请描述您的想法，该功能的意义、作用

去除 potion 产生的状态效果

### 备注信息
> 需要额外说明的内容

当我在实现 "持有物品时获得状态效果" 时，意识到取消持有物品时无法通过action去除状态效果
如果使用"admin: effect ${player.name} clear"，则会返回一条碍眼的消息
![QQ20241026-154541](https://github.com/user-attachments/assets/eb3d5366-21c4-4334-8ffc-ba248f4ea1e7)

**Comment by rokukoo** [comment]
感谢您的反馈，请及时注意交流群中的版本更新。
