### ISSUE TITLE
✨[Feature]一些功能建议

### ISSUE THREAD

**Issue by Clexus** [rokukoo/AzureFlow-issues#24]
官方WIKI：https://rokuko.gitbook.io/azureflow

### 反馈须知
- [x] 已查阅wiki不存在该功能

### 功能描述
> 触发器：onEquip

虽然本身并没有装备物品事件，但是可以通过监听多个事件整合成一个事件，方便使用，同时支持检测是装备上还是取下

> onDamage

受伤时触发

> onSneak, onRun

如题

> 优化onConsume

众所周知，在高版本由于物品组件的加入，消耗功能变化较大，可以拓展一下

>兼容[RPGItems](https://github.com/NyaaCat/RPGitems-reloaded)?

rpgitems在高版本复活，但是由于其对物品的绑定性和功能复杂性，转换为af物品貌似不太可能？所以想问问af能不能添加对rpgitems的兼容？比如可以识别rpg物品并在af文件里对其进行功能拓展等等

### 备注信息
无

**Comment by rokukoo** [comment]
对于onEquip/onUnEquip触发器，您可以使用onPlaceSlotIn与onPlaceSlotOut实现，具体可参阅文档

对于onDamage触发器，从严格意义上来说该触发器的触发时机与物品无关，但AF提供了基于拦截器实现的事件转发功能，onDamage的示例已在交流群中分享

对于onSneak, onRun触发器，我们已记录并添加进下一个版本的更新计划，感谢您的反馈！

其次针对高版本更新的组件相关功能还请等待一段时间，我们需要等待API稳定后再进行相关更新！

**Comment by rokukoo** [comment]
感谢您的反馈，请及时注意交流群中的版本更新。
