### ISSUE TITLE
🐛 [BUG] yaml

### ISSUE THREAD

**Issue by lozinOtus** [rokukoo/AzureFlow-issues#26]
官方WIKI：https://rokuko.gitbook.io/azureflow
描述清晰，排版整洁，错误日志详细的反馈通常会优先处理

### 反馈须知
- [√] 我已详细查阅wiki
- [√] 我已正确安装相关依赖

### 服务端类型
> 请填写您的服务端类型与Minecraft版本
> 如：spigot-1.16.5、paper-1.18.2

paper-1.12.2
--------------------------------------

### 错误描述
> 请详细地描述您遇到的问题

使用yaml增强语法,update后会丢失使用语法的data数据

### 错误日志
> 建议将错误日志上传至 https://paste.ubuntu.com/
> 并以链接形式提交

无

### 备注信息
> 需要额外说明的内容

无

**Comment by rokukoo** [comment]
感谢您的反馈，请及时注意交流群中的版本更新。
