### ISSUE TITLE
🐛 [BUG] 1.8.8加载出错

### ISSUE THREAD

**Issue by YsGqHY** [rokukoo/AzureFlow-issues#27]
官方WIKI：https://rokuko.gitbook.io/azureflow
描述清晰，排版整洁，错误日志详细的反馈通常会优先处理

### 反馈须知
- [X] 我已详细查阅wiki
- [X] 我已正确安装相关依赖

### 服务端类型
> 请填写您的服务端类型与Minecraft版本
> 如：spigot-1.16.5、paper-1.18.2

Spigot-1.8.8
--------------------------------------

### 错误描述
> 请详细地描述您遇到的问题

监听器预注册出问题了

### 错误日志
> 建议将错误日志上传至 https://paste.ubuntu.com/
> 并以链接形式提交

[日志](https://mclo.gs/3jQ1ldX)

### 备注信息
> 需要额外说明的内容

无

**Comment by rokukoo** [comment]
感谢您的反馈，请及时注意交流群中的版本更新。
