### ISSUE TITLE
✨[Feature] onTick触发器

### ISSUE THREAD

**Issue by Clexus** [rokukoo/AzureFlow-issues#28]
官方WIKI：https://rokuko.gitbook.io/azureflow

### 反馈须知
- [X] 已查阅wiki不存在该功能

### 功能描述
> 如题，可自定义周期长短和触发位置

### 备注信息
无

**Comment by rokukoo** [comment]
该触发器已在[TriggerExt](触发器拓展)附属中实现，请移步附属群获取

**Comment by rokukoo** [comment]
感谢您的反馈，请及时注意交流群中的版本更新。
