### ISSUE TITLE
✨[Feature] 添加CustomModelData

### ISSUE THREAD

**Issue by ZeroExact** [rokukoo/AzureFlow-issues#3]
官方WIKI：https://rokuko.gitbook.io/azureflow

### 反馈须知
- [X] 已查阅wiki不存在该功能

### 功能描述
> 请描述您的想法，该功能的意义、作用

快！加！

### 备注信息
> 需要额外说明的内容

无

**Comment by rokukoo** [comment]
预计将在1.0.2.2版本完成, 介时可通过 option.custom_model_data 配置项设置。

感谢您的建议，请及时注意交流群中的版本更新。

**Comment by rokukoo** [comment]
1.0.2.2-rc1-build-30228 版本已支持
