### ISSUE TITLE
✨[Feature] 添加HideFlags 隐藏标签

### ISSUE THREAD

**Issue by luoxiawuchen** [rokukoo/AzureFlow-issues#4]
官方WIKI：https://rokuko.gitbook.io/azureflow

### 反馈须知
- [X] 已查阅wiki不存在该功能

### 功能描述
> 请描述您的想法，该功能的意义、作用

允许设置HideFlags 隐藏物品部分信息，HideFlags:<参数>

```
参数在1~63之间,
1=附魔；
2=属性修饰符；
4=无法破坏；
8=能破坏的方块；
16=能放在的方块；
32=其他，比如药水效果；
63=所有资料。
```

除了物品名称和介绍，需要隐藏2种信息，比如说无法破坏和能破坏的方块就输入12，也就是4+8 
**该段描述参考自：https://www.bilibili.com/read/cv13636973/ 作者：iu1hwu**

感谢六子大佬的耐心阅读🌟

### 备注信息
> 需要额外说明的内容

无

**Comment by rokukoo** [comment]
在早期以及现在的版本中, AzureFlow 为了避免视图层渲染效果与预期不符，默认隐藏物品所有信息。
预计在之后的版本中将添加该配置项, 且位于 display.option 的子节点下。

感谢您的建议，请及时注意交流群中的版本更新。

**Comment by rokukoo** [comment]
在 1.0.2.3 版本中添加了 `display.option.hide` 节点，使用方法大致如下：
```yml
display:
  option:
    hide:
      unbreakable: false
      placed_on: false
      # ...
```

同时，支持枚举值如下：
- enchants: 隐藏附魔属性
- attributes: 隐藏属性加成
- unbreakable: 隐藏不可破坏信息
- destroys: 隐藏可破坏方块信息
- placed_on: 隐藏可放置方块信息
- potion_effects: 隐藏效果信息
- dye: 隐藏染色信息（目前仅1.14+支持该配置项）

值得一提的是，以上默认值均为false，即默认不显示任何信息。
