### ISSUE TITLE
✨[Feature] 添加condition 物品使用条件

### ISSUE THREAD

**Issue by luoxiawuchen** [rokukoo/AzureFlow-issues#5]
官方WIKI：https://rokuko.gitbook.io/azureflow

### 反馈须知
- [X] 已查阅wiki不存在该功能

### 功能描述
> 请描述您的想法，该功能的意义、作用

看了看wiki似乎只有在action动作项目下才能进行check分支判断。
请问能否添加一个类似condition的选项呢？来判定玩家能否使用此物品。

当不满足条件时，这个物品的任何属性都是无效的，无法造成伤害、执行action等。
（或者也可以设定为无法穿戴（装备）、无法使用（物品），使用后物品无效，不执行伤害并自动切换至下一格快捷栏）

同时可以兼容af-state附属，不满足条件时，afs制作的属性失效
例如：用afs制作了一些属性（物理伤害、生命力、防御力等），设定物品使用条件为：需要职业-战士、需要等级-5；不满足时，这些afs属性不生效。

最后，感谢六子大佬的耐心阅读🌟

### 备注信息
> 需要额外说明的内容

无

**Comment by rokukoo** [comment]
该功能将不会直接提供，但用户可以自行制作模板物品集成实现物品使用条件的功能。
大致思路是通过 `action` + `check函数` 来实现判断条件是否可行，您可以在之后的官方模板物品样例中查看。

感谢您的建议，请及时注意交流群中的版本更新。
