### ISSUE TITLE
✨[Feature] 添加AttributeModifiers 属性修饰符

### ISSUE THREAD

**Issue by luoxiawuchen** [rokukoo/AzureFlow-issues#8]
官方WIKI：https://rokuko.gitbook.io/azureflow

### 反馈须知
- [X] 已查阅wiki不存在该功能

### 功能描述
> 请描述您的想法，该功能的意义、作用

属性修饰符，可以用于修饰原版属性，例如让木棍也能拥有伤害与攻击速度，又或者让这些原版武器的伤害得到改变，同时还能规定这些mc原版属性生效的槽位等。

通过属性修饰可以把剑自带的伤害”去掉“，或者做一些模板武器类型：
- 巨剑（初始伤害高，攻速慢）
- 重甲（提供不同的击退抗性）

相关应用还有很多，也可以单纯作为一种属性来用于RPG（但afs不香么）

内容比较多，感谢六佬的耐心阅读！🌟

### 备注信息
> 需要额外说明的内容

以下内容参自[https://www.bilibili.com/read/cv13636973/ 作者：iu1hwu]

在NBT标签中，AttributeModifiers 有以下参数
```
{
AttributeModifiers:[
{Operation:布值b,
Amount:双精d,
UUID:[I;1214111111,1222222322,1333333334,1444445444],
Slot:位置,
AttributeName:"属性",Name:"属性"}
]
} 
```

**Amount: 数值**
表示被修饰属性的数值，和Operation配合使用
允许多个，但强烈建议只填写一个，填多了会很绕，填多少就会加多少属性值

**Operation：**
0表示增加，
1表示以基础值*(1+Amount数值+Amount数值)有多少个Amount数值就会增加多少个,
2表示基础值*(1+Amount数值)*(1+Amount数值) 

**UUID:**
一个整型数组，一共4组，每组8位整数，基本上是随便填的，
直接复制上面的就可以用了，没有什么特殊意义，但不建议让多个属性修饰符的UUID相同，
有极小概率出现未知错误。

**Slot：**
槽位，属性生效的槽位，在主手装备时生命值提升，放副手无效果
槽位类型：mainhand - 主手、offhand - 副手、head - 头、chest - 身、legs - 腿、feet - 脚

**AttributeName&Name：**
算是有些意义不明的设计，Name填相同属性名即可，主要判定的应该是AttributeName值
原版属性类型：（也可以通过/data 查询）
```
generic.max_health(最大生命值) 0~1024

generic.attack_damage（攻击伤害）0~2048

generic.follow_range（生物的追踪距离）0~2048

generic.movement_speed（移动速度）0~1024 这个属性挺迷的，也不知道具体如何运算的，有时候实际值会比这个值大

generic.knockback_resistance（击退抗性) 0~1.0

generic.armor（护甲）0~30

generic.attack_knockback（击退）疣猪兽/劫掠兽/僵尸疣猪兽可用

generic.armor_toughness（护甲韧性）0~20

generic.attack_speed（攻击速度）仅玩家,0~1024

generic.luck（幸运值）仅玩家，-1024~1024

horse.jump_strength(弹跳力)只用于马，跳跃高度,0~1.0

generic.flying_speed (飞行速度) 只用于鹦鹉,0~1024

zombie.spawn_reinforcements(生成援军) 仅僵尸/僵尸猪灵，僵尸收到攻击会尝试生成新的僵尸

```

**Comment by rokukoo** [comment]
感谢您的建议，请及时注意交流群中的版本更新。
